apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp9-deployment
  namespace: tp9-ns
  labels:
    app: tp9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tp9
  template:
    metadata:
      labels:
        app: tp9
    spec:
      containers:
      - name: tp9
        image: ingssoria/tp-9-image:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: tp9-volume
          mountPath: /usr/src/app/db
      volumes:
      - name: tp9-volume
        persistentVolumeClaim:
          claimName: tp9-pvc
