apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp9-deployment
  namespace: tp9-ns
  labels:
    app: tp9
spec:  
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: tp9
  template:
    metadata:
      labels:
        app: tp9
    spec:       
      containers:
      - name: tp9    
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"        
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: tp9-volume
          mountPath: /usr/src/app/db
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http          
      volumes:
      - name: tp9-volume
        persistentVolumeClaim:
          claimName: tp9-pvc
