name: Build and Push Docker Image - TP-9

on:
  push:
    branches: [ "main" ]
    paths: 
      - "DevOps_BootCamp_EIT/tree/TP_9/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "DevOps_BootCamp_EIT/tree/TP_9/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set date as image tag
      id: date
      run: echo "::set-output name=date::$(date +%Y-%m-%d)"

    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: ${{ github.workspace }}/DevOps_BootCamp_EIT/TP_9/
        file: ${{ github.workspace }}/DevOps_BootCamp_EIT/TP_9/Dockerfile
        no-cache: true
        push: false
        tags: ingssoria/tp-9-image:${{ steps.date.outputs.date }}-${{ github.run_number }}